"""
Build a multi-page PDF report of the Toronto Weather dashboard using reportlab,
reusing the matplotlib chart PNGs generated by build_charts.py.
"""
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                 Image as RLImage, PageBreak, HRFlowable)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER

with open('../dashboard_data.json') as f:
    DATA = json.load(f)

kpis = DATA['kpis']
monthly = DATA['monthly']

styles = getSampleStyleSheet()
styles.add(ParagraphStyle('TitleBig', parent=styles['Title'], fontSize=22, textColor=colors.HexColor('#10263d')))
styles.add(ParagraphStyle('SubTitle', parent=styles['Normal'], fontSize=10.5, textColor=colors.HexColor('#6b7785')))
styles.add(ParagraphStyle('H2', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#10263d'), spaceBefore=14, spaceAfter=8))
styles.add(ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=15))

doc = SimpleDocTemplate('Toronto_Weather_Dashboard_Report.pdf', pagesize=letter,
                         leftMargin=0.6*inch, rightMargin=0.6*inch, topMargin=0.55*inch, bottomMargin=0.55*inch)

story = []

# ---- Cover / header with logo ----
logo = RLImage('../assets/dabeltech_logo_cleaned.png', width=0.9*inch, height=0.9*inch)
header_tbl = Table([[Paragraph("Toronto Weather Analytics — 2012", styles['TitleBig']), logo]],
                    colWidths=[5.6*inch, 1.0*inch])
header_tbl.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'MIDDLE'), ('ALIGN', (1,0), (1,0), 'RIGHT')]))
story.append(header_tbl)
story.append(Paragraph("Hourly climate dataset · 8,784 observations · Jan 1 - Dec 31, 2012 (leap year)", styles['SubTitle']))
story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e6e9ec'), spaceBefore=8, spaceAfter=14))

# ---- KPI table ----
kpi_data = [
    ["Avg Temp", "Max Temp", "Min Temp", "Avg Humidity", "Avg Wind", "Precip Hours"],
    [f"{kpis['avg_temp']}°C", f"{kpis['max_temp']}°C", f"{kpis['min_temp']}°C",
     f"{kpis['avg_humidity']}%", f"{kpis['avg_wind']} km/h", f"{kpis['pct_precip_hours']}%"],
]
kpi_tbl = Table(kpi_data, colWidths=[1.13*inch]*6)
kpi_tbl.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#10263d')),
    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ('FONTSIZE', (0,0), (-1,-1), 9),
    ('FONTSIZE', (0,1), (-1,1), 13),
    ('FONTNAME', (0,1), (-1,1), 'Helvetica-Bold'),
    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ('BOTTOMPADDING', (0,0), (-1,0), 6),
    ('TOPPADDING', (0,0), (-1,0), 6),
    ('TOPPADDING', (0,1), (-1,1), 8),
    ('BOTTOMPADDING', (0,1), (-1,1), 8),
    ('BACKGROUND', (0,1), (-1,1), colors.HexColor('#f4f6f8')),
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e6e9ec')),
]))
story.append(kpi_tbl)
story.append(Spacer(1, 16))

# ---- Charts, two per page in a 2x1 stack, matching dashboard grouping ----
chart_pairs = [
    ("Monthly Temperature Trend", 'chart_monthly_temp.png', "Weather Condition Mix", 'chart_condition.png'),
    ("Diurnal Temperature Pattern", 'chart_hourly.png', "Precipitation Hours by Season", 'chart_season_precip.png'),
    ("Humidity vs Wind Speed", 'chart_humidity_wind.png', "Correlation with Temperature", 'chart_correlation.png'),
]

for t1, p1, t2, p2 in chart_pairs:
    story.append(Paragraph(t1, styles['H2']))
    story.append(RLImage(p1, width=6.3*inch, height=6.3*inch*0.42))
    story.append(Spacer(1, 6))
    story.append(Paragraph(t2, styles['H2']))
    story.append(RLImage(p2, width=6.3*inch, height=6.3*inch*0.42))
    story.append(PageBreak())

story.append(Paragraph("Daily Temperature Range (Full Year 2012)", styles['H2']))
story.append(RLImage('chart_daily_range.png', width=6.3*inch, height=6.3*inch*0.34))
story.append(Spacer(1, 14))

# ---- Monthly summary table ----
story.append(Paragraph("Monthly Summary", styles['H2']))
table_data = [["Month", "Avg Temp", "Max", "Min", "Humidity %", "Wind km/h", "Pressure kPa", "Precip Hrs"]]
for m in monthly:
    table_data.append([m['MonthName'], f"{m['avg_temp']}", f"{m['max_temp']}", f"{m['min_temp']}",
                        f"{m['avg_humidity']}", f"{m['avg_wind']}", f"{m['avg_pressure']}", f"{m['precip_hours']}"])
mtbl = Table(table_data, colWidths=[0.65*inch]+[0.82*inch]*7, repeatRows=1)
mtbl.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#10263d')),
    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ('FONTSIZE', (0,0), (-1,-1), 8),
    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ('GRID', (0,0), (-1,-1), 0.4, colors.HexColor('#e6e9ec')),
    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8f9fa')]),
]))
story.append(mtbl)
story.append(PageBreak())

# ---- Summary narrative ----
story.append(Paragraph("Analysis Summary", styles['H2']))
summary_points = [
    f"<b>Strong seasonality:</b> average temperature swings from about -7.4°C in January to roughly 21-22°C in "
    f"summer, an annual range of {kpis['annual_temp_range']}°C between the single hottest "
    f"({kpis['max_temp']}°C, June) and coldest ({kpis['min_temp']}°C, January) hours recorded.",

    f"<b>Predominantly dry/clear conditions:</b> roughly {kpis['pct_clear_hours']}% of all hours were clear or "
    f"mainly clear, while only {kpis['pct_precip_hours']}% had active precipitation (rain, snow, drizzle, or "
    f"freezing variants) and {kpis['pct_fog_hours']}% had fog/haze.",

    "<b>Winter is the wettest/foggiest season</b> by hour-count (highest precipitation hours), while summer is "
    "driest despite being warmest — typical of a continental pattern where winter precipitation is more "
    "persistent (snow) even if less intense.",

    "<b>Humidity and wind are inversely related to visibility:</b> humidity correlates at r &asymp; -0.63 with "
    "visibility, and pressure drops are associated with higher wind speeds (r &asymp; -0.36) — both physically "
    "expected relationships that validate data integrity.",

    "<b>Dew point tracks temperature almost perfectly</b> (r &asymp; 0.93), as expected physically, while pressure "
    "and temperature show a mild negative relationship, reflecting more low-pressure (stormy) systems arriving "
    "in cooler months.",

    "<b>Diurnal cycle:</b> temperatures trough in the early morning (~5-6 AM) and peak in mid-afternoon (~3-4 PM), "
    "a normal solar heating pattern.",
]
for p in summary_points:
    story.append(Paragraph("• " + p, styles['Body']))
    story.append(Spacer(1, 6))

story.append(Spacer(1, 10))
story.append(Paragraph(
    "<b>Data quality:</b> the dataset was already clean — zero nulls, zero duplicate timestamps, complete hourly "
    "coverage across the full leap year, and no out-of-range values (humidity 0-100%, non-negative wind/visibility). "
    "Cleaning consisted of standardizing column names, parsing the datetime field, and deriving categorical/time "
    "features (season, hour, primary weather condition, precipitation/fog flags) to support this analysis.",
    styles['Body']))

story.append(Spacer(1, 20))
story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e6e9ec')))
story.append(Spacer(1, 6))
story.append(Paragraph("Source: Environment Canada hourly climate station data (2012). "
                        "Report generated with Python (pandas, matplotlib, reportlab). · dabelinfotech",
                        styles['SubTitle']))

doc.build(story)
print("PDF built.")
